# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfafa82d37c8a609b4471c6a9dc9079b28dd338b49a482d770c2a898956c35e9515ff6a17dda13689586b2dfa56efa83f8b30b812514fb67cf69583a45d1dffa

test:
  secret_key_base: 34984ca80a44505ed66f4a78aaa9ffbc8e693f400c1d3bdc3175aeb0ff7c852397480019ebee4110485c823bb01e1665b4a9a33c29110c22a56a5e3b09d3ec02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
